variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

cache:
  key: $CI_COMMIT_REF_SLUG-$CI_JOB_NAME
  paths:
    - $PIP_CACHE_DIR

stages:
  - test

image: python:3

black:
  script:
    - pip install --upgrade black
    - black --check .

mypy:
  script:
    - pip install --upgrade mypy
    - mypy --install-types --non-interactive .
