stages:
  - test

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.pip

default:
  image: python:3
  before_script:
    - pip install --upgrade poetry
    - poetry config virtualenvs.in-project true
    - poetry update
  cache:
    key: poetry-install
    paths:
      - .venv
      - $PIP_CACHE_DIR

black:
  script:
    - poetry run black --check .

mypy:
  script:
    - poetry run mypy .
