name: publish

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      uses: ./.github/actions/install-deps
    - name: Build
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build
    - uses: actions/upload-artifact@v4
      with:
        path: ./dist

  pypi-publish:
    needs: ['build']
    runs-on: ubuntu-latest
    environment: 'release'
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/
