name: publish

on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: ./.github/actions/install-deps
    - name: Build and publish
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
