name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PY_COLORS: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-deps
      - run: poetry run tox -e black,mypy,pylint
  unit:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-deps
      - name: Run unit tests
        run: poetry run tox -e pytest-unit
